# importing library

In [10]:
import numpy as np

# Array attributes

In [92]:
a= np.array([1,2,3,4,5]) # 1-D / vector

In [93]:
a

array([1, 2, 3, 4, 5])

In [94]:
type(a)

numpy.ndarray

In [95]:
a.shape

(5,)

In [18]:
a.ndim


1

In [64]:
b = np.array([[1,2,3,4], # 2-D / metrix
              [2,4,6,8]])

In [20]:
b

array([[1, 2, 3, 4],
       [2, 4, 6, 8]])

In [21]:
type(b)

numpy.ndarray

In [22]:
b.shape

(2, 4)

In [23]:
b.ndim

2

In [38]:
c = np.array([[[1.0,2,3],
               [2,3,4],
               [4,6,7]]])
d= np.array([[[3,5,8],
              [2,4,5],
              [3,4,5]],
             [[10,11,12],
              [13,14,15],
              [16,17,18]]])
              

In [96]:
c , d

(array([[[1., 2., 3.],
         [2., 3., 4.],
         [4., 6., 7.]]]),
 array([[[ 3,  5,  8],
         [ 2,  4,  5],
         [ 3,  4,  5]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [97]:
type(c), type(d)

(numpy.ndarray, numpy.ndarray)

In [98]:
c.shape, d.shape

((1, 3, 3), (2, 3, 3))

In [99]:
c.ndim, d.ndim

(3, 3)

In [100]:
a.dtype, b.dtype, c.dtype, d.dtype

(dtype('int32'), dtype('int32'), dtype('float64'), dtype('int32'))

In [101]:
a.size,b.size,c.size,d.size # determine how many array elements are there an array.

(5, 8, 9, 18)

In [102]:
a.data, b.data, c.data, d.data

(<memory at 0x000001DB939D9B40>,
 <memory at 0x000001DB9AA14310>)

In [156]:
a.nbytes,b.nbytes,c.nbytes,d.nbytes # total bytes consumed by the elements of an array.

(20, 32, 72, 72)

# Array creation

In [157]:
array1 = np.array([1,2,3],dtype = 'int')

In [158]:
array1

array([1, 2, 3])

In [159]:
zeros = np.zeros((3,3), dtype = 'float')

In [160]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [161]:
ones = np.ones((3,3),dtype = 'int')

In [162]:
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [163]:
full = np.full((2,3), 5)

In [164]:
full

array([[5, 5, 5],
       [5, 5, 5]])

In [165]:
identity = np.identity(3, dtype = 'int')

In [166]:
identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [167]:
eye = np.eye(3,3, -1)

In [168]:
eye

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [169]:
arange = np.arange(1, 10,2)

In [170]:
arange

array([1, 3, 5, 7, 9])

In [171]:
linspace = np.linspace(1,100,50, dtype  = 'int')

In [172]:
linspace

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97, 100])

In [173]:
linspace.size

50

In [174]:
empty  = np.empty((1,5))

In [175]:
empty

array([[0., 1., 2., 3., 4.]])

In [176]:
for i in range(5):
    empty[:,i] = i
empty

array([[0., 1., 2., 3., 4.]])

# Array indexing slicing

# Indexing 

In [177]:
arr1 = np.array([1,2,3,4,5])

In [178]:
print(arr1)

[1 2 3 4 5]


In [179]:
arr1[0]

1

In [180]:
arr1[3]

4

In [181]:
arr1[-1]

5

In [182]:
arr1[-3]

3

In [187]:
arr2 = np.random.randint(1,10,size =(3,3))

In [188]:
arr2

array([[6, 2, 8],
       [9, 7, 6],
       [7, 4, 5]])

In [189]:
arr2[0][0]

6

In [192]:
arr2[0][1]

2

In [194]:
arr2[1][1]

7

In [195]:
arr2[1][0]

9

In [196]:
arr2[0,1]

2

In [197]:
arr2[1,0]

9

In [198]:
arr3 = np.random.randint(1,10, size =(2,3,3))

In [199]:
arr3

array([[[5, 6, 6],
        [1, 7, 6],
        [1, 4, 1]],

       [[9, 6, 8],
        [3, 2, 4],
        [4, 7, 6]]])

In [200]:
arr3[0][0][0]

5

In [202]:
arr3[1][0][0]

9

In [203]:
arr3[1,2,1]

7

# Slicing

In [204]:
print(arr1)

[1 2 3 4 5]


In [207]:
print(arr1[0:3])

[1 2 3]


In [209]:
print(arr1[2:])

[3 4 5]


In [210]:
arr2

array([[6, 2, 8],
       [9, 7, 6],
       [7, 4, 5]])

In [212]:
print(arr2[0:2,0:2])

[[6 2]
 [9 7]]


In [214]:
print(arr2[1:, 1:])

[[7 6]
 [4 5]]


# Manupilating array shapes
1. reshape()
2. resize()
3. ravel()
4. flatten()
5. defining array shape

### reshape()

In [255]:
a = np.array([[1,2,3],
              [4,5,6]])

In [256]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [257]:
a.shape

(2, 3)

In [258]:
a_reshaped = np.reshape(a,(3,2))

In [259]:
a_reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])

In [260]:
a_reshaped.shape

(3, 2)

### resize()

In [261]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [262]:
a_resized = np.resize(a, (3,3))

In [263]:
a_resized

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [264]:
a_resized2 = np.resize(a, (3,2))

In [265]:
a_resized2

array([[1, 2],
       [3, 4],
       [5, 6]])

### ravel()

In [281]:
a = np.random.randint(1,10,(2,3))

In [282]:
a

array([[8, 7, 7],
       [8, 9, 5]])

In [298]:
a_raveled = np.ravel(a) # return a view of the array.

In [299]:
a_raveled

array([0, 7, 7, 8, 9, 5])

In [300]:
a_raveled.shape

(6,)

In [301]:
a_raveled[0] = 0

In [302]:
a_raveled

array([0, 7, 7, 8, 9, 5])

In [303]:
a

array([[0, 7, 7],
       [8, 9, 5]])

### flatten()

In [304]:
a

array([[0, 7, 7],
       [8, 9, 5]])

In [315]:
a_flattened = a.flatten() # return a copy of the array, always allocates a new memory.

In [316]:
a_flattened

array([0, 7, 7, 8, 9, 5])

In [317]:
a_flattened[0] = 100

In [318]:
a_flattened

array([100,   7,   7,   8,   9,   5])

In [319]:
a

array([[0, 7, 7],
       [8, 9, 5]])

### defining an array shape

In [320]:
a

array([[0, 7, 7],
       [8, 9, 5]])

In [322]:
a.shape = (3,2)

In [323]:
a

array([[0, 7],
       [7, 8],
       [9, 5]])

# Array stacking

### horizontal stacking

In [338]:
a = np.arange(1,10).reshape(3,3)

In [339]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [340]:
b = 2*a

In [341]:
b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [342]:
np.hstack((a,b))

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [343]:
np.column_stack((a,b))

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [344]:
np.concatenate((a,b), axis = 1)

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

### vertical stacking

In [346]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [347]:
np.row_stack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [348]:
np.concatenate((a,b), axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

### depth stack

In [349]:
np.dstack((a,b))

array([[[ 1,  2],
        [ 2,  4],
        [ 3,  6]],

       [[ 4,  8],
        [ 5, 10],
        [ 6, 12]],

       [[ 7, 14],
        [ 8, 16],
        [ 9, 18]]])